export { default as AddBookings } from './bookings/AddBooking';
export {default as BookingList} from './bookings/BookingList'
export { default as CustomerManagement } from './customers/CustomerManagement';
export { default as AddCustomer } from './customers/AddCustomer';
export { default as DriversList } from './drivers/DriversList';
export { default as AddDriver } from './drivers/AddDriver';
export { default as AddIncomeexpense } from './incomeexpense/AddIncomeexpense';
export { default as IeManagement } from './incomeexpense/IeManagement';
export { default as MaintenanceList } from './maintenance/MaintenanceList';
export { default as AddMaintenance } from './maintenance/AddMaintenance';
export { default as ReminderPanel } from './reminders/ReminderPanel';
export { default as AddReminder } from './reminders/AddReminder';
export { default as ReportList } from './reports/ReportList';
export { default as AddReport } from './reports/AddReport';
export { default as Settings } from './Settings';
export { default as LiveTracking } from './tracking/LiveTracking';
export { default as HistoryTracking } from './tracking/HistoryTracking';
export { default as UserPanel } from './users/UserPanel';
export { default as AddUser } from './users/AddUser';
export { default as AddVehicle } from './vehicles/AddVehicle';
export { default as VehicleGroup } from './vehicles/VehicleGroup';
export { default as VehicleList } from './vehicles/VehicleList';
export { default as Availability } from './Availability';
export { default as AdminDashboard } from './AdminDashboard';
export { default as AdminLogin } from './AdminLogin';
export {default as LandingPage} from '../landingPages/LandingPage';